### ISSUE TITLE
[Help] Need compatibility with nginx/1.16.1

### ISSUE THREAD

**Issue by prawen** [openresty/headers-more-nginx-module#108]
Hello,

Facing issue with using more_clear_input_headers on nginx/1.16.1

Error:
nginx: [emerg] unknown directive "more_clear_headers" in /etc/nginx/nginx.conf

OS: Ubuntu 16.04 Xenial

Installed nginx from https://nginx.org/en/linux_packages.html#Ubuntu

Upgraded nginx from 1.10.3 to 1.16.1

When upgraded, it removed nginx-common and nginx-extras packages. Not sure why.

Please help.

**Comment by rainingmaster** [comment]
@prawen 
Hello, I think it because you install `nginx` instead of instead `openresty`? Official Nginx maybe not compile with `headers-more-nginx-module`.  You can try to search it like this: `nginx -V 2>&1 | grep headers-more`.

I suggest you [install Openresty from official repo](https://openresty.org/en/installation.html), and it has compile with `headers-more-nginx-module` already.
