### ISSUE TITLE
修改了last_modified无效

### ISSUE THREAD

**Issue by talktoto** [openresty/headers-more-nginx-module#31]
我试着修改了last_modified参数，但是他却没有生效，如下所示
	more_set_headers "Last-Modified:Mon, 02 Mar 2015 14:38:11 GMT";
	more_set_headers "Etag:54f475d1-7";

如下是测试结果：（他尽然返回的还是HTTP/1.1 200 OK）
MKdeMacBook-Air:Downloads tototalk$ curl -H "If-Modified-Since:Mon, 02 Mar 2015 14:38:11 GMT" -I http://test.mk.com
HTTP/1.1 200 OK
Server: nginx/1.6.2
Date: Mon, 02 Mar 2015 15:49:19 GMT
Content-Type: text/html
Content-Length: 6
Connection: keep-alive
ETag: 54f475d1-7
Last-Modified: Mon, 02 Mar 2015 14:38:11 GMT
Cache-Control: max-age=120
Accept-Ranges: bytes

下面是我返回正确的last_modified结果：
MKdeMacBook-Air:Downloads tototalk$ curl -H "If-Modified-Since:Mon, 02 Mar 2015 14:38:09 GMT" -I http://test.mk.com
HTTP/1.1 304 Not Modified
Server: nginx/1.6.2
Date: Mon, 02 Mar 2015 15:50:52 GMT
Connection: keep-alive
ETag: 54f475d1-7
Last-Modified: Mon, 02 Mar 2015 14:38:11 GMT
Cache-Control: max-age=120

请问这个问题如何处理啊。

**Comment by agentzh** [comment]
@talktoto Please, no Chinese here. This place is supposed to be English only. Please use the openresty (Chinese) mailing list if you really want to use Chinese (but please do not cross-post).

Regarding your question, 304 responses are usually generated by nginx's standard ngx_http_not_modified_module's header filter, which always runs before this ngx_headers_more module's. That's why you're not seeing 304 here because when ngx_http_not_modified_module is run, your `more_set_headers` directive has not run yet.

**Comment by talktoto** [comment]
Thank you very much
You help me solve a big of problems.
