### ISSUE TITLE
nginx 1.8.1 使用more_clear_headers 过滤信息无效

### ISSUE THREAD

**Issue by aaasayok** [openresty/headers-more-nginx-module#53]
你好！我是一名新手，对nginx也是刚了解，昨天按照一篇教程 在我本地上测试， 发现headers_more_nginx_module好像不生效， 下面是我的nginx 信息

nginx version: nginx/1.8.1
built by gcc 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)
built with OpenSSL 1.0.2f  28 Jan 2016
TLS SNI support enabled
configure arguments: --prefix=/usr/local/webserver/nginx --with-http_ssl_module --with-pcre=/usr/local/src/pcre-8.38 --with-zlib=/usr/local/src/zlib-1.2.8 --with-openssl=/usr/local/src/openssl-1.0.2f --add-module=/usr/local/src/headers-more-nginx-module-0.30rc1

**Comment by agentzh** [comment]
@aaasayok Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.

Regarding your issue. Maybe you are invoking the wrong nginx from your nginx startup script? Better use the absolute path of the nginx executable in your `init` script or something like that because the `PATH` environment may take different values in that context.
