### ISSUE TITLE
Overriding Cache-Control , Expires and Last-Modified headers

### ISSUE THREAD

**Issue by kamalkp** [openresty/headers-more-nginx-module#84]
Hello agentzh,
                        just to clear the confusion : 
Unlike the standard headers module, this module does not automatically take care of the constraint among the Expires, Cache-Control, and Last-Modified headers. You have to get them right yourself or use the headers module together with this module.

Does this module allow overriding the Cache-Control , Expires and Last-Modified headers . 
It didn't work for me.

        location /dummy/path/css {
                more_set_headers        "Cache-Control: max-age=1800";
                proxy_pass http://x.x.x.x ;
        }

[root@]# curl -I https://www.xxxxxxxxx.com/dummy/path/css --insecure
HTTP/1.1 404 Not Found
Server: xxxxxxxx
Content-Type: text/html; charset=iso-8859-1
Connection: keep-alive
Date: xxxxxxxxxxxxxxxxxxx
X-Page-Speed: 1.11.33.4-0
Cache-Control: max-age=0, no-cache

Does this module not allow overriding these 3 headers, or am I doing something wrong?

Thanks,

**Comment by agentzh** [comment]
@kamalkp I just added a standalone test case using proxy module and headers more module only and your example works beautifully:

https://github.com/openresty/headers-more-nginx-module/blob/master/t/bug.t#L397

I'm seeing the "x-Page-Speed" thing in your response output. I guess it is because you are using some 3rd-party filter modules like `ngx_pagespeed` which runs *after* our header more module's output filter and thus overriding the response header set by your `more_set_headers` directive.

**Comment by kamalkp** [comment]
Thank you for your reply agentzh!
I have been investigating this issue, I made a separate test environment for that and got the override working. So, no problems with the header override module.
Also investigated with pagespeed installed, It works regardless.

I believe there is some issue with the CDN environment that I am working on. Not sure yet, still investigating.
Will update here when I find something.

Thanks again!
